#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.0 effective-5.10 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
#ifndef DEENISLAMSDK_SWIFT_H
#define DEENISLAMSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFoundation;
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="DeenIslamSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

typedef SWIFT_ENUM(NSInteger, AppFeature, open) {
  AppFeatureHome = 0,
  AppFeatureDua = 1,
  AppFeatureHadith = 2,
  AppFeatureTasbeeh = 3,
  AppFeatureAlQuaran = 4,
  AppFeatureIslamicName = 5,
  AppFeaturePrayerTime = 6,
  AppFeatureQibla = 7,
  AppFeatureZakat = 8,
  AppFeatureIslamicEvent = 9,
  AppFeatureNearestMosque = 10,
  AppFeatureEidJamatPlace = 11,
  AppFeatureNamazLearning = 12,
  AppFeatureMoccaModinaLive = 13,
  AppFeatureDuaAndAmol = 14,
  AppFeatureIslamicLearningStory = 15,
  AppFeatureRamadan = 16,
  AppFeatureRramadan = 17,
  AppFeatureHajjAndUmrah = 18,
  AppFeatureKhotomQuran = 19,
  AppFeatureQurbani = 20,
  AppFeatureIslamicBoyan = 21,
  AppFeatureIslamicCalender = 22,
  AppFeatureLivePodcast = 23,
  AppFeatureAllahNames = 24,
};

@class NSString;
@class NSNumber;
@class MPMediaItemArtwork;

/// An <code>AudioItem</code> instance contains every piece of information needed for an <code>AudioPlayer</code> to play.
/// URLs can be remote or local.
SWIFT_CLASS("_TtC12DeenIslamSDK9AudioItem")
@interface AudioItem : NSObject
/// The artist of the item.
/// This can change over time which is why the property is dynamic. It enables KVO on the property.
@property (nonatomic, copy) NSString * _Nullable artist;
/// The title of the item.
/// This can change over time which is why the property is dynamic. It enables KVO on the property.
@property (nonatomic, copy) NSString * _Nullable title;
/// The album of the item.
/// This can change over time which is why the property is dynamic. It enables KVO on the property.
@property (nonatomic, copy) NSString * _Nullable album;
/// The track count of the item’s album.
/// This can change over time which is why the property is dynamic. It enables KVO on the property.
@property (nonatomic, strong) NSNumber * _Nullable trackCount;
/// The track number of the item in its album.
/// This can change over time which is why the property is dynamic. It enables KVO on the property.
@property (nonatomic, strong) NSNumber * _Nullable trackNumber;
@property (nonatomic, strong) MPMediaItemArtwork * _Nullable artwork;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



/// An <code>AudioPlayer</code> instance is used to play <code>AudioPlayerItem</code>. It’s an easy to use AVPlayer with simple methods to
/// handle the whole playing audio process.
/// You can get events (such as state change or time observation) by registering a delegate.
SWIFT_CLASS("_TtC12DeenIslamSDK11AudioPlayer")
@interface AudioPlayer : NSObject
/// Initializes a new AudioPlayer.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end













/// Represents the strategy used for buffering of items before playback is started
typedef SWIFT_ENUM(NSInteger, AudioPlayerBufferingStrategy, open) {
/// Uses the default AVPlayer buffering strategy, which buffers very aggressively before starting playback.
/// This often leads to start of playback being delayed more than necessary.
  AudioPlayerBufferingStrategyDefaultBuffering = 0,
/// Uses a strategy better at quickly starting playback. Duration to buffer before playback is customizable through
/// the <code>preferredBufferDurationBeforePlayback</code> variable. Requires iOS/tvOS 10+ to have any effect.
  AudioPlayerBufferingStrategyPlayWhenPreferredBufferDurationFull = 1,
/// Uses a strategy that simply starts playback whenever the AVPlayerItem buffer is non-empty. Requires iOS/tvOS 10+ to have any effect.
  AudioPlayerBufferingStrategyPlayWhenBufferNotEmpty = 2,
};

@class NSCoder;

SWIFT_CLASS("_TtC12DeenIslamSDK8BaseView")
@interface BaseView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end







SWIFT_PROTOCOL("_TtP12DeenIslamSDK20DeenIslamSDKNotifier_")
@protocol DeenIslamSDKNotifier <NSObject>
/// \param isValid if token is valid <code>true</code> else <code>false</code>
///
/// \param error if token is invalid throw error
///
- (void)tokenStatusWithToken:(BOOL)isValid error:(NSString * _Nullable)error;
/// Description
/// \param error any error occure this func call with error message
///
- (void)errorMessageWithError:(NSString * _Nonnull)error;
- (void)deenPaymentEventWithEventName:(NSString * _Nonnull)eventName parameters:(NSDictionary<NSString *, NSString *> * _Nonnull)parameters;
@end




@class UIColor;

SWIFT_CLASS("_TtC12DeenIslamSDK8DropDown")
@interface DropDown : UITextField
@property (nonatomic) IBInspectable CGFloat rowHeight;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull rowBackgroundColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull itemsColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull itemsTintColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull selectedRowColor;
@property (nonatomic) IBInspectable BOOL hideOptionsWhenSelect;
@property (nonatomic) IBInspectable BOOL isSearchEnable;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull borderColorr;
@property (nonatomic) IBInspectable CGFloat listHeight;
@property (nonatomic) IBInspectable CGFloat borderWidth;
@property (nonatomic) IBInspectable CGFloat cornerRadius;
@property (nonatomic) IBInspectable CGFloat arrowSize;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull arrowColor;
@property (nonatomic) IBInspectable BOOL checkMarkEnabled;
@property (nonatomic) IBInspectable BOOL handleKeyboard;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)touchAction;
@end

@class UITableView;
@class NSIndexPath;

@interface DropDown (SWIFT_EXTENSION(DeenIslamSDK)) <UITableViewDelegate>
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

@class UITableViewCell;

@interface DropDown (SWIFT_EXTENSION(DeenIslamSDK)) <UITableViewDataSource>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface DropDown (SWIFT_EXTENSION(DeenIslamSDK)) <UITextFieldDelegate>
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldDidBeginEditing:(UITextField * _Nonnull)textField;
- (BOOL)textFieldShouldBeginEditing:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
@end



SWIFT_CLASS("_TtC12DeenIslamSDK16LayoutConstraint")
@interface LayoutConstraint : NSLayoutConstraint
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface LayoutConstraint (SWIFT_EXTENSION(DeenIslamSDK))
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end







SWIFT_CLASS("_TtC12DeenIslamSDK7NoorSDK")
@interface NoorSDK : NSObject
@property (nonatomic, readonly) BOOL isInitialized;
/// initilizer
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@class UITabBarController;
@class UINavigationController;
@class UIEvent;

@interface NoorSDK (SWIFT_EXTENSION(DeenIslamSDK))
/// \param msisdn user mobile number
///
/// \param isBL number is BL or not
///
- (void)logInWith:(NSString * _Nonnull)msisdn complete:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable))complete;
/// \param tabBar UITabBarController for quran show
///
/// \param nav UINavigationController for navigate view controller
///
/// \param delegate DeenIslamSDKNotifier for sdk error and state notifier
///
/// \param token String SDK initilize token
///
/// \param isBL initialize number is BL or not
///
- (void)initializeWith:(UITabBarController * _Nullable)tabBar nav:(UINavigationController * _Nonnull)nav delegate:(id <DeenIslamSDKNotifier> _Nonnull)delegate token:(NSString * _Nonnull)token isBL:(BOOL)isBL;
- (void)gotoHomeWithTabBar:(UITabBarController * _Nullable)tabBar nav:(UINavigationController * _Nonnull)nav;
- (void)gotoWithFeature:(enum AppFeature)feature tabBar:(UITabBarController * _Nullable)tabBar nav:(UINavigationController * _Nonnull)nav;
- (void)eventRegisterWith:(UIEvent * _Nonnull)event;
- (void)terminate;
- (void)openFromRCWithCode:(NSString * _Nonnull)code;
- (BOOL)isPrayerNotificationEnabled SWIFT_WARN_UNUSED_RESULT;
- (void)clearAllPrayerNotification;
- (void)prayerNotificationWithIsEnable:(BOOL)isEnable;
- (void)logout;
@end









@interface UIButton (SWIFT_EXTENSION(DeenIslamSDK))
- (UIView * _Nullable)hitTest:(CGPoint)point withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
@end










































SWIFT_CLASS("_TtC12DeenIslamSDK8VGPlayer")
@interface VGPlayer : NSObject
- (nonnull instancetype)init;
@end


@interface VGPlayer (SWIFT_EXTENSION(DeenIslamSDK))
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)change context:(void * _Nullable)context;
@end





SWIFT_CLASS("_TtC12DeenIslamSDK26VGPlayerCacheConfiguration")
@interface VGPlayerCacheConfiguration : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12DeenIslamSDK20VGPlayerCacheManager")
@interface VGPlayerCacheManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12DeenIslamSDK18VGPlayerCacheMedia")
@interface VGPlayerCacheMedia : NSObject <NSCoding>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12DeenIslamSDK31VGPlayerCacheMediaConfiguration")
@interface VGPlayerCacheMediaConfiguration : NSObject <NSCoding, NSCopying>
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC12DeenIslamSDK24VGPlayerCacheMediaWorker")
@interface VGPlayerCacheMediaWorker : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC12DeenIslamSDK20VGPlayerCacheSession")
@interface VGPlayerCacheSession : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12DeenIslamSDK28VGPlayerDownloadActionWorker")
@interface VGPlayerDownloadActionWorker : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@class NSURLSession;
@class NSURLSessionDataTask;
@class NSURLResponse;
@class NSData;
@class NSURLSessionTask;

SWIFT_CLASS("_TtC12DeenIslamSDK33VGPlayerDownloadURLSessionManager")
@interface VGPlayerDownloadURLSessionManager : NSObject <NSURLSessionDataDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session dataTask:(NSURLSessionDataTask * _Nonnull)dataTask didReceiveResponse:(NSURLResponse * _Nonnull)response completionHandler:(void (^ _Nonnull)(NSURLSessionResponseDisposition))completionHandler;
- (void)URLSession:(NSURLSession * _Nonnull)session dataTask:(NSURLSessionDataTask * _Nonnull)dataTask didReceiveData:(NSData * _Nonnull)data;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didCompleteWithError:(NSError * _Nullable)error;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC12DeenIslamSDK18VGPlayerDownloader")
@interface VGPlayerDownloader : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC12DeenIslamSDK24VGPlayerLoadingIndicator")
@interface VGPlayerLoadingIndicator : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end


SWIFT_CLASS("_TtC12DeenIslamSDK22VGPlayerResourceLoader")
@interface VGPlayerResourceLoader : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC12DeenIslamSDK29VGPlayerResourceLoaderManager")
@interface VGPlayerResourceLoaderManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@class AVAssetResourceLoader;
@class AVAssetResourceLoadingRequest;

@interface VGPlayerResourceLoaderManager (SWIFT_EXTENSION(DeenIslamSDK)) <AVAssetResourceLoaderDelegate>
- (BOOL)resourceLoader:(AVAssetResourceLoader * _Nonnull)resourceLoader shouldWaitForLoadingOfRequestedResource:(AVAssetResourceLoadingRequest * _Nonnull)loadingRequest SWIFT_WARN_UNUSED_RESULT;
- (void)resourceLoader:(AVAssetResourceLoader * _Nonnull)resourceLoader didCancelLoadingRequest:(AVAssetResourceLoadingRequest * _Nonnull)loadingRequest;
@end


SWIFT_CLASS("_TtC12DeenIslamSDK30VGPlayerResourceLoadingRequest")
@interface VGPlayerResourceLoadingRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC12DeenIslamSDK14VGPlayerSlider")
@interface VGPlayerSlider : UISlider
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (CGRect)thumbRectForBounds:(CGRect)bounds trackRect:(CGRect)rect value:(float)value SWIFT_WARN_UNUSED_RESULT;
- (CGRect)trackRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC12DeenIslamSDK12VGPlayerView")
@interface VGPlayerView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end


@class UIGestureRecognizer;
@class UITouch;

@interface VGPlayerView (SWIFT_EXTENSION(DeenIslamSDK)) <UIGestureRecognizerDelegate>
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldReceiveTouch:(UITouch * _Nonnull)touch SWIFT_WARN_UNUSED_RESULT;
@end




@class UITapGestureRecognizer;
@class UIPanGestureRecognizer;

@interface VGPlayerView (SWIFT_EXTENSION(DeenIslamSDK))
/// Single Tap Event
/// \param gesture Single Tap Gesture
///
- (void)onSingleTapGesture:(UITapGestureRecognizer * _Nonnull)gesture;
/// Double Tap Event
/// \param gesture Double Tap Gesture
///
- (void)onDoubleTapGesture:(UITapGestureRecognizer * _Nonnull)gesture;
/// Pan Event
/// \param gesture Pan Gesture
///
- (void)onPanGesture:(UIPanGestureRecognizer * _Nonnull)gesture;
@end

@class WKWebView;
@class WKNavigationAction;

/// Embed and control YouTube videos
SWIFT_CLASS("_TtC12DeenIslamSDK17YouTubePlayerView")
@interface YouTubePlayerView : UIView <WKNavigationDelegate>
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 6.0 effective-5.10 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
#ifndef DEENISLAMSDK_SWIFT_H
#define DEENISLAMSDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AVFoundation;
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
@import WebKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="DeenIslamSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

typedef SWIFT_ENUM(NSInteger, AppFeature, open) {
  AppFeatureHome = 0,
  AppFeatureDua = 1,
  AppFeatureHadith = 2,
  AppFeatureTasbeeh = 3,
  AppFeatureAlQuaran = 4,
  AppFeatureIslamicName = 5,
  AppFeaturePrayerTime = 6,
  AppFeatureQibla = 7,
  AppFeatureZakat = 8,
  AppFeatureIslamicEvent = 9,
  AppFeatureNearestMosque = 10,
  AppFeatureEidJamatPlace = 11,
  AppFeatureNamazLearning = 12,
  AppFeatureMoccaModinaLive = 13,
  AppFeatureDuaAndAmol = 14,
  AppFeatureIslamicLearningStory = 15,
  AppFeatureRamadan = 16,
  AppFeatureRramadan = 17,
  AppFeatureHajjAndUmrah = 18,
  AppFeatureKhotomQuran = 19,
  AppFeatureQurbani = 20,
  AppFeatureIslamicBoyan = 21,
  AppFeatureIslamicCalender = 22,
  AppFeatureLivePodcast = 23,
  AppFeatureAllahNames = 24,
};

@class NSString;
@class NSNumber;
@class MPMediaItemArtwork;

/// An <code>AudioItem</code> instance contains every piece of information needed for an <code>AudioPlayer</code> to play.
/// URLs can be remote or local.
SWIFT_CLASS("_TtC12DeenIslamSDK9AudioItem")
@interface AudioItem : NSObject
/// The artist of the item.
/// This can change over time which is why the property is dynamic. It enables KVO on the property.
@property (nonatomic, copy) NSString * _Nullable artist;
/// The title of the item.
/// This can change over time which is why the property is dynamic. It enables KVO on the property.
@property (nonatomic, copy) NSString * _Nullable title;
/// The album of the item.
/// This can change over time which is why the property is dynamic. It enables KVO on the property.
@property (nonatomic, copy) NSString * _Nullable album;
/// The track count of the item’s album.
/// This can change over time which is why the property is dynamic. It enables KVO on the property.
@property (nonatomic, strong) NSNumber * _Nullable trackCount;
/// The track number of the item in its album.
/// This can change over time which is why the property is dynamic. It enables KVO on the property.
@property (nonatomic, strong) NSNumber * _Nullable trackNumber;
@property (nonatomic, strong) MPMediaItemArtwork * _Nullable artwork;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



/// An <code>AudioPlayer</code> instance is used to play <code>AudioPlayerItem</code>. It’s an easy to use AVPlayer with simple methods to
/// handle the whole playing audio process.
/// You can get events (such as state change or time observation) by registering a delegate.
SWIFT_CLASS("_TtC12DeenIslamSDK11AudioPlayer")
@interface AudioPlayer : NSObject
/// Initializes a new AudioPlayer.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end













/// Represents the strategy used for buffering of items before playback is started
typedef SWIFT_ENUM(NSInteger, AudioPlayerBufferingStrategy, open) {
/// Uses the default AVPlayer buffering strategy, which buffers very aggressively before starting playback.
/// This often leads to start of playback being delayed more than necessary.
  AudioPlayerBufferingStrategyDefaultBuffering = 0,
/// Uses a strategy better at quickly starting playback. Duration to buffer before playback is customizable through
/// the <code>preferredBufferDurationBeforePlayback</code> variable. Requires iOS/tvOS 10+ to have any effect.
  AudioPlayerBufferingStrategyPlayWhenPreferredBufferDurationFull = 1,
/// Uses a strategy that simply starts playback whenever the AVPlayerItem buffer is non-empty. Requires iOS/tvOS 10+ to have any effect.
  AudioPlayerBufferingStrategyPlayWhenBufferNotEmpty = 2,
};

@class NSCoder;

SWIFT_CLASS("_TtC12DeenIslamSDK8BaseView")
@interface BaseView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@end







SWIFT_PROTOCOL("_TtP12DeenIslamSDK20DeenIslamSDKNotifier_")
@protocol DeenIslamSDKNotifier <NSObject>
/// \param isValid if token is valid <code>true</code> else <code>false</code>
///
/// \param error if token is invalid throw error
///
- (void)tokenStatusWithToken:(BOOL)isValid error:(NSString * _Nullable)error;
/// Description
/// \param error any error occure this func call with error message
///
- (void)errorMessageWithError:(NSString * _Nonnull)error;
- (void)deenPaymentEventWithEventName:(NSString * _Nonnull)eventName parameters:(NSDictionary<NSString *, NSString *> * _Nonnull)parameters;
@end




@class UIColor;

SWIFT_CLASS("_TtC12DeenIslamSDK8DropDown")
@interface DropDown : UITextField
@property (nonatomic) IBInspectable CGFloat rowHeight;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull rowBackgroundColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull itemsColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull itemsTintColor;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull selectedRowColor;
@property (nonatomic) IBInspectable BOOL hideOptionsWhenSelect;
@property (nonatomic) IBInspectable BOOL isSearchEnable;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull borderColorr;
@property (nonatomic) IBInspectable CGFloat listHeight;
@property (nonatomic) IBInspectable CGFloat borderWidth;
@property (nonatomic) IBInspectable CGFloat cornerRadius;
@property (nonatomic) IBInspectable CGFloat arrowSize;
@property (nonatomic, strong) IBInspectable UIColor * _Nonnull arrowColor;
@property (nonatomic) IBInspectable BOOL checkMarkEnabled;
@property (nonatomic) IBInspectable BOOL handleKeyboard;
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)touchAction;
@end

@class UITableView;
@class NSIndexPath;

@interface DropDown (SWIFT_EXTENSION(DeenIslamSDK)) <UITableViewDelegate>
- (void)tableView:(UITableView * _Nonnull)tableView didSelectRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath;
@end

@class UITableViewCell;

@interface DropDown (SWIFT_EXTENSION(DeenIslamSDK)) <UITableViewDataSource>
- (NSInteger)tableView:(UITableView * _Nonnull)tableView numberOfRowsInSection:(NSInteger)section SWIFT_WARN_UNUSED_RESULT;
- (UITableViewCell * _Nonnull)tableView:(UITableView * _Nonnull)tableView cellForRowAtIndexPath:(NSIndexPath * _Nonnull)indexPath SWIFT_WARN_UNUSED_RESULT;
@end


@interface DropDown (SWIFT_EXTENSION(DeenIslamSDK)) <UITextFieldDelegate>
- (BOOL)textFieldShouldReturn:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (void)textFieldDidBeginEditing:(UITextField * _Nonnull)textField;
- (BOOL)textFieldShouldBeginEditing:(UITextField * _Nonnull)textField SWIFT_WARN_UNUSED_RESULT;
- (BOOL)textField:(UITextField * _Nonnull)textField shouldChangeCharactersInRange:(NSRange)range replacementString:(NSString * _Nonnull)string SWIFT_WARN_UNUSED_RESULT;
@end



SWIFT_CLASS("_TtC12DeenIslamSDK16LayoutConstraint")
@interface LayoutConstraint : NSLayoutConstraint
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@interface LayoutConstraint (SWIFT_EXTENSION(DeenIslamSDK))
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@end







SWIFT_CLASS("_TtC12DeenIslamSDK7NoorSDK")
@interface NoorSDK : NSObject
@property (nonatomic, readonly) BOOL isInitialized;
/// initilizer
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@class UITabBarController;
@class UINavigationController;
@class UIEvent;

@interface NoorSDK (SWIFT_EXTENSION(DeenIslamSDK))
/// \param msisdn user mobile number
///
/// \param isBL number is BL or not
///
- (void)logInWith:(NSString * _Nonnull)msisdn complete:(void (^ _Nonnull)(NSString * _Nullable, NSString * _Nullable))complete;
/// \param tabBar UITabBarController for quran show
///
/// \param nav UINavigationController for navigate view controller
///
/// \param delegate DeenIslamSDKNotifier for sdk error and state notifier
///
/// \param token String SDK initilize token
///
/// \param isBL initialize number is BL or not
///
- (void)initializeWith:(UITabBarController * _Nullable)tabBar nav:(UINavigationController * _Nonnull)nav delegate:(id <DeenIslamSDKNotifier> _Nonnull)delegate token:(NSString * _Nonnull)token isBL:(BOOL)isBL;
- (void)gotoHomeWithTabBar:(UITabBarController * _Nullable)tabBar nav:(UINavigationController * _Nonnull)nav;
- (void)gotoWithFeature:(enum AppFeature)feature tabBar:(UITabBarController * _Nullable)tabBar nav:(UINavigationController * _Nonnull)nav;
- (void)eventRegisterWith:(UIEvent * _Nonnull)event;
- (void)terminate;
- (void)openFromRCWithCode:(NSString * _Nonnull)code;
- (BOOL)isPrayerNotificationEnabled SWIFT_WARN_UNUSED_RESULT;
- (void)clearAllPrayerNotification;
- (void)prayerNotificationWithIsEnable:(BOOL)isEnable;
- (void)logout;
@end









@interface UIButton (SWIFT_EXTENSION(DeenIslamSDK))
- (UIView * _Nullable)hitTest:(CGPoint)point withEvent:(UIEvent * _Nullable)event SWIFT_WARN_UNUSED_RESULT;
@end










































SWIFT_CLASS("_TtC12DeenIslamSDK8VGPlayer")
@interface VGPlayer : NSObject
- (nonnull instancetype)init;
@end


@interface VGPlayer (SWIFT_EXTENSION(DeenIslamSDK))
- (void)observeValueForKeyPath:(NSString * _Nullable)keyPath ofObject:(id _Nullable)object change:(NSDictionary<NSKeyValueChangeKey, id> * _Nullable)change context:(void * _Nullable)context;
@end





SWIFT_CLASS("_TtC12DeenIslamSDK26VGPlayerCacheConfiguration")
@interface VGPlayerCacheConfiguration : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12DeenIslamSDK20VGPlayerCacheManager")
@interface VGPlayerCacheManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12DeenIslamSDK18VGPlayerCacheMedia")
@interface VGPlayerCacheMedia : NSObject <NSCoding>
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12DeenIslamSDK31VGPlayerCacheMediaConfiguration")
@interface VGPlayerCacheMediaConfiguration : NSObject <NSCoding, NSCopying>
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder;
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (id _Nonnull)copyWithZone:(struct _NSZone * _Nullable)zone SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly, copy) NSString * _Nonnull debugDescription;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC12DeenIslamSDK24VGPlayerCacheMediaWorker")
@interface VGPlayerCacheMediaWorker : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC12DeenIslamSDK20VGPlayerCacheSession")
@interface VGPlayerCacheSession : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC12DeenIslamSDK28VGPlayerDownloadActionWorker")
@interface VGPlayerDownloadActionWorker : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


@class NSURLSession;
@class NSURLSessionDataTask;
@class NSURLResponse;
@class NSData;
@class NSURLSessionTask;

SWIFT_CLASS("_TtC12DeenIslamSDK33VGPlayerDownloadURLSessionManager")
@interface VGPlayerDownloadURLSessionManager : NSObject <NSURLSessionDataDelegate>
- (void)URLSession:(NSURLSession * _Nonnull)session dataTask:(NSURLSessionDataTask * _Nonnull)dataTask didReceiveResponse:(NSURLResponse * _Nonnull)response completionHandler:(void (^ _Nonnull)(NSURLSessionResponseDisposition))completionHandler;
- (void)URLSession:(NSURLSession * _Nonnull)session dataTask:(NSURLSessionDataTask * _Nonnull)dataTask didReceiveData:(NSData * _Nonnull)data;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didCompleteWithError:(NSError * _Nullable)error;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC12DeenIslamSDK18VGPlayerDownloader")
@interface VGPlayerDownloader : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC12DeenIslamSDK24VGPlayerLoadingIndicator")
@interface VGPlayerLoadingIndicator : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end


SWIFT_CLASS("_TtC12DeenIslamSDK22VGPlayerResourceLoader")
@interface VGPlayerResourceLoader : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC12DeenIslamSDK29VGPlayerResourceLoaderManager")
@interface VGPlayerResourceLoaderManager : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


@class AVAssetResourceLoader;
@class AVAssetResourceLoadingRequest;

@interface VGPlayerResourceLoaderManager (SWIFT_EXTENSION(DeenIslamSDK)) <AVAssetResourceLoaderDelegate>
- (BOOL)resourceLoader:(AVAssetResourceLoader * _Nonnull)resourceLoader shouldWaitForLoadingOfRequestedResource:(AVAssetResourceLoadingRequest * _Nonnull)loadingRequest SWIFT_WARN_UNUSED_RESULT;
- (void)resourceLoader:(AVAssetResourceLoader * _Nonnull)resourceLoader didCancelLoadingRequest:(AVAssetResourceLoadingRequest * _Nonnull)loadingRequest;
@end


SWIFT_CLASS("_TtC12DeenIslamSDK30VGPlayerResourceLoadingRequest")
@interface VGPlayerResourceLoadingRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end



SWIFT_CLASS("_TtC12DeenIslamSDK14VGPlayerSlider")
@interface VGPlayerSlider : UISlider
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (CGRect)thumbRectForBounds:(CGRect)bounds trackRect:(CGRect)rect value:(float)value SWIFT_WARN_UNUSED_RESULT;
- (CGRect)trackRectForBounds:(CGRect)bounds SWIFT_WARN_UNUSED_RESULT;
@end


SWIFT_CLASS("_TtC12DeenIslamSDK12VGPlayerView")
@interface VGPlayerView : UIView
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
@end


@class UIGestureRecognizer;
@class UITouch;

@interface VGPlayerView (SWIFT_EXTENSION(DeenIslamSDK)) <UIGestureRecognizerDelegate>
- (BOOL)gestureRecognizer:(UIGestureRecognizer * _Nonnull)gestureRecognizer shouldReceiveTouch:(UITouch * _Nonnull)touch SWIFT_WARN_UNUSED_RESULT;
@end




@class UITapGestureRecognizer;
@class UIPanGestureRecognizer;

@interface VGPlayerView (SWIFT_EXTENSION(DeenIslamSDK))
/// Single Tap Event
/// \param gesture Single Tap Gesture
///
- (void)onSingleTapGesture:(UITapGestureRecognizer * _Nonnull)gesture;
/// Double Tap Event
/// \param gesture Double Tap Gesture
///
- (void)onDoubleTapGesture:(UITapGestureRecognizer * _Nonnull)gesture;
/// Pan Event
/// \param gesture Pan Gesture
///
- (void)onPanGesture:(UIPanGestureRecognizer * _Nonnull)gesture;
@end

@class WKWebView;
@class WKNavigationAction;

/// Embed and control YouTube videos
SWIFT_CLASS("_TtC12DeenIslamSDK17YouTubePlayerView")
@interface YouTubePlayerView : UIView <WKNavigationDelegate>
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (void)layoutSubviews;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
